<a href="https://colab.research.google.com/github/aiswaryajoseph2004-bot/Natural-Language-Processing-NLP-/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Remove stop words

In [ ]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk
nltk.download('stopwords')
nltk.download('punkt_tab')
text='This is a sample sentence.'
words=word_tokenize(text)
filtered=[w for w in words if w.lower() not in stopwords.words('english')]
print(filtered)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


['sample', 'sentence', '.']


# Tokenization

In [ ]:
from nltk.tokenize import word_tokenize
print(word_tokenize('This is a sentence.'))

['This', 'is', 'a', 'sentence', '.']


# Stemming

In [ ]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
print(stemmer.stem('running'))

run


# Lemmatization

In [ ]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
lemmatizer=WordNetLemmatizer()
print(lemmatizer.lemmatize('running',pos='v'))

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


run


In [ ]:
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')
stemmer=PorterStemmer()
lemmatizer=WordNetLemmatizer()

word1='running'
word2='better'
word3='studies'

print('Stemming:')
print(stemmer.stem(word1))
print(stemmer.stem(word2))
print(stemmer.stem(word3))

print('\nLemmatization:')
print(lemmatizer.lemmatize(word1, pos='v'))
print(lemmatizer.lemmatize(word2, pos='a'))
print(lemmatizer.lemmatize(word3, pos='n'))

Stemming:
run
better
studi

Lemmatization:
run
good
study


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


# pos(part of speech) Tagging

In [ ]:
import nltk
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('punkt')

from nltk.tokenize import word_tokenize

tokens=word_tokenize("This is a sample sentence")

print(nltk.pos_tag(tokens))

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


[('This', 'DT'), ('is', 'VBZ'), ('a', 'DT'), ('sample', 'JJ'), ('sentence', 'NN')]


# NER(Name entity recogintion)

In [ ]:
import spacy
nlp = spacy.load('en_core_web_sm')
doc = nlp("Barack Obama was born in Hawaii.")
print([(ent.text, ent.label_) for ent in doc.ents])

[('Barack Obama', 'PERSON'), ('Hawaii', 'GPE')]


In [ ]:
import spacy
nlp = spacy.load("en_core_web_sm")
doc = nlp("Apple is looking at buying U.K. startup for $1 billion")
print([(ent.text,ent.label_) for ent in doc.ents])

[('Apple', 'ORG'), ('U.K.', 'GPE'), ('$1 billion', 'MONEY')]


# chunking

In [ ]:
import nltk
text='The quick brown fox jumps over the lazy dog'
tokens = nltk.word_tokenize(text)
tags=nltk.pos_tag(tokens)
chunk_grammar = "NP: {<DT>?<JJ>*<NN>}"
cp=nltk.RegexpParser(chunk_grammar)
tree = cp.parse(tags)
tree.pretty_print()

                                     S                                 
     ________________________________|______________________            
    |        |              NP               NP             NP         
    |        |       _______|________        |       _______|______     
jumps/VBZ over/IN The/DT quick/JJ brown/NN fox/NN the/DT lazy/JJ dog/NN



# word Embedding or Vectorization

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x=cv.fit_transform(["This is a sample","This is another example"])
print(x.toarray())

[[0 0 1 1 1]
 [1 1 1 0 1]]


In [ ]:
print(cv.get_feature_names_out())

['another' 'example' 'is' 'sample' 'this']


# TF-IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
x = tf.fit_transform(["This is a sample", "This is another example"])
print(tf.get_feature_names_out())
print(x.toarray())

['another' 'example' 'is' 'sample' 'this']
[[0.         0.         0.50154891 0.70490949 0.50154891]
 [0.57615236 0.57615236 0.40993715 0.         0.40993715]]


# countvectorizer to extract n_grams

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
text = ["I love NLP"]
cv = CountVectorizer(ngram_range=(1,3))
X = cv.fit_transform(text)
print(cv.get_feature_names_out())

['love' 'love nlp' 'nlp']


**(1, 1) (default) Only single words (unigrams)

(1, 2) Unigrams and bigrams

(2, 2) Only bigrams

(1, 3) Unigrams, bigrams, and trigrams**

# sentiment analysis

 <b>Polarity: 0.5 </b> <br> <hr>
Range: from -1.0 (most negative) to +1.0 (most positive) <br>
Meaning: A value of 0.5 indicates a moderately positive sentiment. <br>
Negative: < 0 <br>
Neutral: 0 <br>
Positive: > 0 <br>
 <b>Subjectivity: 0.6 </b> <br> <hr>
Range: from 0.0 (objective) to 1.0 (subjective)<br>
Meaning: A value of 0.6 suggests the text is fairly subjective, meaning it's based more on personal opinion or feelings than on factual information.



In [ ]:
from textblob import TextBlob
print(TextBlob("I love this product").sentiment)


Sentiment(polarity=0.5, subjectivity=0.6)


| Term             | Simple meaning                     |
| ---------------- | ---------------------------------- |
| **Polarity**     | How negative or positive it is     |
| **Subjectivity** | How much of it is opinion vs. fact |


| Term             | Range                      | Meaning                                      |
| ---------------- | -------------------------- | -------------------------------------------- |
| **Polarity**     | `-1.0` to `+1.0`           | How **negative** or **positive** the text is |
|                  | `-1.0` → Very negative     | Example: *“I hate this movie.”*              |
|                  | `0.0` → Neutral            | Example: *“It is a movie.”*                  |
|                  | `+1.0` → Very positive     | Example: *“I love this movie!”*              |
|                  |                            |                                              |
| **Subjectivity** | `0.0` to `1.0`             | How much is **opinion** vs. **fact**         |
|                  | `0.0` → Completely factual | Example: *“The sun rises in the east.”*      |
|                  | `1.0` → Fully opinionated  | Example: *“I think this is the best ever!”*  |


# text classification with pipeline

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

#  Example text data (spam detection style)
texts=[
    "Buy now",
    "Limited offer",
    "call me later",
    "meeting at noon",
    "free coupons",
    "Let's have lunch",
    "win a prize now",
    "project discussion tomorrow"
]

labels=[
    "spam",
    "spam",
    "ham",
    "ham",
    "spam",
    "ham",
    "spam",
    "ham"
]
#  Split into training and testing data
x_train,x_test,y_train,y_test = train_test_split(
    texts,labels,test_size=0.25,random_state=42
)
#  Create the pipeline
pipe=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('classifier',MultinomialNB())
])

#  Train the model
pipe.fit(x_train,y_train)

#  Make predictions
preds = pipe.predict(x_test)

#  Evaluate the model
print("Test predictions:", preds)
print("Actual labels:   ", y_test)
print("Accuracy:", accuracy_score(y_test, preds))
#  Try a new example
new_text = ["Congratulations, you won a free ticket!"]
new_pred = pipe.predict(new_text)
print("\nNew text:", new_text[0])
print("Predicted label:", new_pred[0])

Test predictions: ['ham' 'ham']
Actual labels:    ['spam', 'ham']
Accuracy: 0.5

New text: Congratulations, you won a free ticket!
Predicted label: spam


In [ ]:
import pandas as pd


In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/email.csv")
df

Category                                            Message
0                ham  Go until jurong point, crazy.. Available only ...
1                ham                      Ok lar... Joking wif u oni...
2               spam  Free entry in 2 a wkly comp to win FA Cup fina...
3                ham  U dun say so early hor... U c already then say...
4                ham  Nah I don't think he goes to usf, he lives aro...
...              ...                                                ...
5568             ham               Will ü b going to esplanade fr home?
5569             ham  Pity, * was in mood for that. So...any other s...
5570             ham  The guy did some bitching but I acted like i'd...
5571             ham                         Rofl. Its true to its name
5572  {"mode":"full"                                    isActive:false}

[5573 rows x 2 columns]

In [ ]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.model_selection import train_test_split
x=df["Message"]
y=df["Category"]
x_train,x_test,y_train,y_test = train_test_split(
   x,y,test_size=0.25,random_state=42
)

pipe=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('classifier',MultinomialNB())
])


pipe.fit(x_train,y_train)

preds = pipe.predict(x_test)

print("Test predictions:", preds)
print("Actual labels:   ", y_test)
print("Accuracy:", accuracy_score(y_test, preds))
#  Try a new example
new_text = ["Congratulations, you won a free ticket!"]
new_pred = pipe.predict(new_text)
print("\nNew text:", new_text[0])
print("Predicted label:", new_pred[0])

Test predictions: ['ham' 'ham' 'ham' ... 'ham' 'ham' 'ham']
Actual labels:    3690     ham
3527     ham
724      ham
3370     ham
468      ham
        ... 
19      spam
4757     ham
668      ham
218      ham
5395     ham
Name: Category, Length: 1394, dtype: object
Accuracy: 0.9849354375896701

New text: Congratulations, you won a free ticket!
Predicted label: spam
